### ISSUE TITLE
How to add ckpt models?

### ISSUE THREAD

**Issue by elen07zz** [JbPasquier/stable-diffusion-onnx-ui#1]
Hello, how can I add models that I already have downloaded?
im getting this error

(venv) PS H:\stable>
python convert_original_stable_diffusion_to_diffusers.py --checkpoint_path="./model1.ckpt" --dump_path="./model1"
Traceback (most recent call last):
  File "H:\stable\convert_original_stable_diffusion_to_diffusers.py", line 799, in <module>
    global_step = checkpoint["global_step"]
KeyError: 'global_step'
(venv) PS H:\stable>

**Comment by JbPasquier** [comment]
Hi,

You can convert a model this way:

```
python convert_original_stable_diffusion_to_diffusers.py --checkpoint_path="./some_file.ckpt" --dump_path="./some_file"
python convert_stable_diffusion_checkpoint_to_onnx.py --model_path="./some_file" --output_path="model/some_onnx"
```

Where:
* ./some_file.ckpt is the relative path to your ckpt file. You can put an absolute path here too.
* ./some_file is a temporary path, easier to put it next to your ckpt file.
* model/some_onnx is a relative path to where the converted folder will be. It must be on the model folder.

Notice that you need the venv to be loaded and to be on the proper folder.

---

Just saw your last edit, can you provide me the model you're trying to use? I'll try on my side.

**Comment by elen07zz** [comment]
Tried several but same error.
https://sdexchange.net/download/AnythingGape-fp16.ckpt
https://huggingface.co/Deltaadams/HentaiDiffusion/resolve/main/HD-17.ckpt

**Comment by JbPasquier** [comment]
At least for the second one you can use the diffuser version directly from huggingface.

```
python convert_stable_diffusion_checkpoint_to_onnx.py --model_path="Deltaadams/HentaiDiffusion" --output_path="model/hentai_diffusion_onnx"
```

I'll have a look for the other one.

**Comment by elen07zz** [comment]
python convert_stable_diffusion_checkpoint_to_onnx.py --model_path="Deltaadams/HentaiDiffusion" --output_path="model/hentai_diffusion_onnx"

doesnt work :(
Traceback (most recent call last):
  File "H:\stable\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 239, in hf_raise_for_status
    response.raise_for_status()
  File "H:\stable\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/Deltaadams/HentaiDiffusion/resolve/main/model_index.json

**Comment by JbPasquier** [comment]
I just tried to convert both of your links without any issue.

Can you try updating both scripts to the latest versions ?

```
rm convert_original_stable_diffusion_to_diffusers.py
rm convert_stable_diffusion_checkpoint_to_onnx.py
python -m wget https://raw.githubusercontent.com/huggingface/diffusers/main/scripts/convert_original_stable_diffusion_to_diffusers.py -o convert_original_stable_diffusion_to_diffusers.py
python -m wget https://raw.githubusercontent.com/huggingface/diffusers/main/scripts/convert_stable_diffusion_checkpoint_to_onnx.py -o convert_stable_diffusion_checkpoint_to_onnx.py
```

And then run again:

```
python convert_original_stable_diffusion_to_diffusers.py --checkpoint_path="./HD-17.ckpt" --dump_path="./HD-17"
python convert_stable_diffusion_checkpoint_to_onnx.py --model_path="./HD-17" --output_path="model/hd_17_onnx"
```

---

If it still gives you an error, maybe it's an outdated dependency.
Try to update the whole project: Remove venv folder and *.py files and then restart the [First installation](https://github.com/JbPasquier/stable-diffusion-onnx-ui#first-installation) process.

**Comment by elen07zz** [comment]
After trying downloading them again it seems that it finally worked, Thank you.

It seems that the only models that still don't work are those that use .tensor instead of ckpt. I tried to convert them using a tool but it gives me the same error as mentioned before.
But that's probably a tool problem. so case closed.
