### ISSUE TITLE
Crashes with error in module numpy

### ISSUE THREAD

**Issue by benoegen** [JbPasquier/stable-diffusion-onnx-ui#2]
I followed the instructions, but the generation fails with:

` File "D:\StableDiffusion\21_gui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_onnx_stable_diffusion.py", line 250, in __call__
    latents = latents * np.float(self.scheduler.init_noise_sigma)
  File "D:\StableDiffusion\21_gui\venv\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'
`

Any idea how to fix this? Thank you!

**Comment by JbPasquier** [comment]
Thanks,

It's related to an issue with the upstream of diffusers, it will work only when [this PR](https://github.com/huggingface/diffusers/pull/1789) gets merged.

**Comment by GrizCliz** [comment]
You can fix this by just downgrading numpy to version 1.23 (pip install numpy==1.23)

**Comment by benoegen** [comment]
Downgrading worked, also the mentioned PR was merged recently, so it works as described. Thank you!
