### ISSUE TITLE
pytorch for amd (rocm)

### ISSUE THREAD

**Issue by 4cecoder** [JbPasquier/stable-diffusion-onnx-ui#4]
isn't a specific build of pytorch for amd required for gpu?

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/rocm5.2`

https://i.imgur.com/HMhuHFW.png

according to the clickable tool to [install pytorch](https://pytorch.org/)

**Comment by JbPasquier** [comment]
This repository is based on ONNX. See [documentation](https://huggingface.co/docs/diffusers/optimization/onnx).
